olgaDjangoBlog_9_01_2023/djangoblog/accounts/urls.py
from django.urls import include, re_path
from django.urls import path

from . import views
from .forms import LoginForm

app_name = "accounts"

urlpatterns = [re_path(r'^login/$',
                       views.LoginView.as_view(success_url='/'),
                       name='login',
                       kwargs={'authentication_form': LoginForm}),
               re_path(r'^register/$',
                       views.RegisterView.as_view(success_url="/"),
                       name='register'),
               re_path(r'^logout/$',
                       views.LogoutView.as_view(),
                       name='logout'),
               path(r'account/result.html',
                    views.account_result,
                    name='result'),
               re_path(r'^forget_password/$',
                       views.ForgetPasswordView.as_view(),
                       name='forget_password'),
               re_path(r'^forget_password_code/$',
                       views.ForgetPasswordEmailCode.as_view(),
                       name='forget_password_code'),
               ]

olgaDjangoBlog_9_01_2023/djangoblog/blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

app_name = "blog"
urlpatterns = [
    path(
        r'',
        views.IndexView.as_view(),
        name='index'),
    path(
        r'page/<int:page>/',
        views.IndexView.as_view(),
        name='index_page'),
    path(
        r'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html',
        views.ArticleDetailView.as_view(),
        name='detailbyid'),
    path(
        r'category/<slug:category_name>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail'),
    path(
        r'category/<slug:category_name>/<int:page>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail_page'),
    path(
        r'author/<author_name>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail'),
    path(
        r'author/<author_name>/<int:page>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail_page'),
    path(
        r'tag/<slug:tag_name>.html',
        views.TagDetailView.as_view(),
        name='tag_detail'),
    path(
        r'tag/<slug:tag_name>/<int:page>.html',
        views.TagDetailView.as_view(),
        name='tag_detail_page'),
    path(
        'archives.html',
        cache_page(
            60 * 60)(
            views.ArchivesView.as_view()),
        name='archives'),
    path(
        'links.html',
        views.LinkListView.as_view(),
        name='links'),
    path(
        r'upload',
        views.fileupload,
        name='upload'),
]

olgaDjangoBlog_9_01_2023/djangoblog/djangoblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import include
from django.urls import re_path
from haystack.views import search_view_factory

from blog.views import EsSearchView
from djangoblog.admin_site import admin_site
from djangoblog.elasticsearch_backend import ElasticSearchModelSearchForm
from djangoblog.feeds import DjangoBlogFeed
from djangoblog.sitemap import ArticleSiteMap, CategorySiteMap, StaticViewSitemap, TagSiteMap, UserSiteMap

sitemaps = {

    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handle403 = 'blog.views.permission_denied_view'
urlpatterns = [
                  re_path(r'^admin/', admin_site.urls),
                  re_path(r'', include('blog.urls', namespace='blog')),
                  re_path(r'mdeditor/', include('mdeditor.urls')),
                  re_path(r'', include('comments.urls', namespace='comment')),
                  re_path(r'', include('accounts.urls', namespace='account')),
                  re_path(r'', include('oauth.urls', namespace='oauth')),
                  re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
                          name='django.contrib.sitemaps.views.sitemap'),
                  re_path(r'^feed/$', DjangoBlogFeed()),
                  re_path(r'^rss/$', DjangoBlogFeed()),
                  re_path('^search', search_view_factory(view_class=EsSearchView, form_class=ElasticSearchModelSearchForm),
                          name='search'),
                  re_path(r'', include('servermanager.urls', namespace='servermanager')),
                  re_path(r'', include('owntracks.urls', namespace='owntracks'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

olgaDjangoBlog_9_01_2023/djangoblog/owntracks/urls.py
from django.urls import path

from . import views

app_name = "owntracks"

urlpatterns = [
    path('owntracks/logtracks', views.manage_owntrack_log, name='logtracks'),
    path('owntracks/show_maps', views.show_maps, name='show_maps'),
    path('owntracks/get_datas', views.get_datas, name='get_datas'),
    path('owntracks/show_dates', views.show_log_dates, name='show_dates')
]

olgaDjangoBlog_9_01_2023/djangoblog/comments/models.py
from django.conf import settings
from django.db import models
from django.utils.timezone import now

from blog.models import Article


# Create your models here.

class Comment(models.Model):
    body = models.TextField('текст', max_length=300)
    created_time = models.DateTimeField('время создания', default=now)
    last_mod_time = models.DateTimeField('Изменить время', default=now)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='автор',
        on_delete=models.CASCADE)
    article = models.ForeignKey(
        Article,
        verbose_name='статья',
        on_delete=models.CASCADE)
    parent_comment = models.ForeignKey(
        'self',
        verbose_name="превосходные комментарии",
        blank=True,
        null=True,
        on_delete=models.CASCADE)
    is_enable = models.BooleanField(
        'отображать ли', default=True, blank=False, null=False)

    class Meta:
        ordering = ['-id']
        verbose_name = "Комментарий"
        verbose_name_plural = verbose_name
        get_latest_by = 'id'

    def __str__(self):
        return self.body

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

olgaDjangoBlog_9_01_2023/djangoblog/blog/forms.py
import logging

from django import forms
from haystack.forms import SearchForm

logger = logging.getLogger(__name__)


class BlogSearchForm(SearchForm):
    querydata = forms.CharField(required=True)

    def search(self):
        datas = super(BlogSearchForm, self).search()
        if not self.is_valid():
            return self.no_query_found()

        if self.cleaned_data['querydata']:
            logger.info(self.cleaned_data['querydata'])
        return datas

olgaDjangoBlog_9_01_2023/djangoblog/blog/views.py
import logging
import os
import uuid

from django.conf import settings
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from haystack.views import SearchView

from blog.models import Article, Category, LinkShowType, Links, Tag
from comments.forms import CommentForm
from djangoblog.utils import cache, get_blog_setting, get_sha256

logger = logging.getLogger(__name__)


class ArticleListView(ListView):
    # template_name
    # Атрибут используется для указания, какой шаблон использовать для рендеринга.
    template_name = 'blog/article_index.html'

    # context_object_name
    # Атрибут используется для именования переменной контекста (используйте это имя в шаблоне).
    context_object_name = 'article_list'

    # Тип страницы, категория или список тегов и т. д.
    page_type = ''
    paginate_by = settings.PAGINATE_BY
    page_kwarg = 'page'
    link_type = LinkShowType.L

    def get_view_cache_key(self):
        return self.request.get['pages']

    @property
    def page_number(self):
        page_kwarg = self.page_kwarg
        page = self.kwargs.get(
            page_kwarg) or self.request.GET.get(page_kwarg) or 1
        return page

    def get_queryset_cache_key(self):
        """
        переопределение подкласса queryset тайник key
        """
        raise NotImplementedError()

    def get_queryset_data(self):
        """
        подкласс override.Get queryset Данные
        """
        raise NotImplementedError()

    def get_queryset_from_cache(self, cache_key):
        '''
        кэшировать данные страницы
        :param cache_key: кеш-ключ
        :return:
        '''
        value = cache.get(cache_key)
        if value:
            logger.info('get view cache.key:{key}'.format(key=cache_key))
            return value
        else:
            article_list = self.get_queryset_data()
            cache.set(cache_key, article_list)
            logger.info('set view cache.key:{key}'.format(key=cache_key))
            return article_list

    def get_queryset(self):
        '''
        Переопределить значение по умолчанию, получить данные из кеша
        :return:
        '''
        key = self.get_queryset_cache_key()
        value = self.get_queryset_from_cache(key)
        return value

    def get_context_data(self, **kwargs):
        kwargs['linktype'] = self.link_type
        return super(ArticleListView, self).get_context_data(**kwargs)


class IndexView(ArticleListView):
    '''
    титульная страница
    '''
    # Тип дружбы
    link_type = LinkShowType.I

    def get_queryset_data(self):
        article_list = Article.objects.filter(type='a', status='p')
        return article_list

    def get_queryset_cache_key(self):
        cache_key = 'index_{page}'.format(page=self.page_number)
        return cache_key


class ArticleDetailView(DetailView):
    '''
    Страница сведений о статье
    '''
    template_name = 'blog/article_detail.html'
    model = Article
    pk_url_kwarg = 'article_id'
    context_object_name = "article"

    def get_object(self, queryset=None):
        obj = super(ArticleDetailView, self).get_object()
        obj.viewed()
        self.object = obj
        return obj

    def get_context_data(self, **kwargs):
        comment_form = CommentForm()

        article_comments = self.object.comment_list()
        parent_comments = article_comments.filter(parent_comment=None)
        blog_setting = get_blog_setting()
        paginator = Paginator(parent_comments, blog_setting.article_comment_count)
        page = self.request.GET.get('comment_page', '1')
        if not page.isnumeric():
            page = 1
        else:
            page = int(page)
            if page < 1:
                page = 1
            if page > paginator.num_pages:
                page = paginator.num_pages

        p_comments = paginator.page(page)
        next_page = p_comments.next_page_number() if p_comments.has_next() else None
        prev_page = p_comments.previous_page_number() if p_comments.has_previous() else None

        if next_page:
            kwargs[
                'comment_next_page_url'] = self.object.get_absolute_url() + f'?comment_page={next_page}#commentlist-container'
        if prev_page:
            kwargs[
                'comment_prev_page_url'] = self.object.get_absolute_url() + f'?comment_page={prev_page}#commentlist-container'
        kwargs['form'] = comment_form
        kwargs['article_comments'] = article_comments
        kwargs['p_comments'] = p_comments
        kwargs['comment_count'] = len(
            article_comments) if article_comments else 0

        kwargs['next_article'] = self.object.next_article
        kwargs['prev_article'] = self.object.prev_article

        return super(ArticleDetailView, self).get_context_data(**kwargs)


class CategoryDetailView(ArticleListView):
    '''
    Список категорий
    '''
    page_type = "Категория Архивы"

    def get_queryset_data(self):
        slug = self.kwargs['category_name']
        category = get_object_or_404(Category, slug=slug)

        categoryname = category.name
        self.categoryname = categoryname
        categorynames = list(
            map(lambda c: c.name, category.get_sub_categorys()))
        article_list = Article.objects.filter(
            category__name__in=categorynames, status='p')
        return article_list

    def get_queryset_cache_key(self):
        slug = self.kwargs['category_name']
        category = get_object_or_404(Category, slug=slug)
        categoryname = category.name
        self.categoryname = categoryname
        cache_key = 'category_list_{categoryname}_{page}'.format(
            categoryname=categoryname, page=self.page_number)
        return cache_key

    def get_context_data(self, **kwargs):

        categoryname = self.categoryname
        try:
            categoryname = categoryname.split('/')[-1]
        except BaseException:
            pass
        kwargs['page_type'] = CategoryDetailView.page_type
        kwargs['tag_name'] = categoryname
        return super(CategoryDetailView, self).get_context_data(**kwargs)


class AuthorDetailView(ArticleListView):
    '''
    Страница сведений об авторе
    '''
    page_type = 'Архив авторских статей'

    def get_queryset_cache_key(self):
        from uuslug import slugify
        author_name = slugify(self.kwargs['author_name'])
        cache_key = 'author_{author_name}_{page}'.format(
            author_name=author_name, page=self.page_number)
        return cache_key

    def get_queryset_data(self):
        author_name = self.kwargs['author_name']
        article_list = Article.objects.filter(
            author__username=author_name, type='a', status='p')
        return article_list

    def get_context_data(self, **kwargs):
        author_name = self.kwargs['author_name']
        kwargs['page_type'] = AuthorDetailView.page_type
        kwargs['tag_name'] = author_name
        return super(AuthorDetailView, self).get_context_data(**kwargs)


class TagDetailView(ArticleListView):
    '''
    Страница со списком тегов
    '''
    page_type = 'Категория Архив тегов'

    def get_queryset_data(self):
        slug = self.kwargs['tag_name']
        tag = get_object_or_404(Tag, slug=slug)
        tag_name = tag.name
        self.name = tag_name
        article_list = Article.objects.filter(
            tags__name=tag_name, type='a', status='p')
        return article_list

    def get_queryset_cache_key(self):
        slug = self.kwargs['tag_name']
        tag = get_object_or_404(Tag, slug=slug)
        tag_name = tag.name
        self.name = tag_name
        cache_key = 'tag_{tag_name}_{page}'.format(
            tag_name=tag_name, page=self.page_number)
        return cache_key

    def get_context_data(self, **kwargs):
        # tag_name = self.kwargs['tag_name']
        tag_name = self.name
        kwargs['page_type'] = TagDetailView.page_type
        kwargs['tag_name'] = tag_name
        return super(TagDetailView, self).get_context_data(**kwargs)


class ArchivesView(ArticleListView):
    '''
    Article Archive Page
    '''
    page_type = 'Архив статей'
    paginate_by = None
    page_kwarg = None
    template_name = 'blog/article_archives.html'

    def get_queryset_data(self):
        return Article.objects.filter(status='p').all()

    def get_queryset_cache_key(self):
        cache_key = 'archives'
        return cache_key


class LinkListView(ListView):
    model = Links
    template_name = 'blog/links_list.html'

    def get_queryset(self):
        return Links.objects.filter(is_enable=True)


class EsSearchView(SearchView):
    def get_context(self):
        paginator, page = self.build_page()
        context = {
            "query": self.query,
            "form": self.form,
            "page": page,
            "paginator": paginator,
            "suggestion": None,
        }
        if hasattr(self.results, "query") and self.results.query.backend.include_spelling:
            context["suggestion"] = self.results.query.get_spelling_suggestion()
        context.update(self.extra_context())

        return context


@csrf_exempt
def fileupload(request):
    """
    Этот метод требует написания вызывающего терминала
    для самостоятельной загрузки изображения,
    этот метод обеспечивает только функцию кровати с изображением.
    :param request:
    :return:
    """
    if request.method == 'POST':
        sign = request.GET.get('sign', None)
        if not sign:
            return HttpResponseForbidden()
        if not sign == get_sha256(get_sha256(settings.SECRET_KEY)):
            return HttpResponseForbidden()
        response = []
        for filename in request.FILES:

olgaDjangoBlog_9_01_2023/djangoblog/templates/blog/tags/article_info.html
{% load blog_tags %}
{% load cache %}
<article id="post-{{ article.pk }} "
         class="post-{{ article.pk }} post type-post status-publish format-standard hentry">
    <header class="entry-header">

        <h1 class="entry-title">
            {% if  isindex %}
                {% if article.article_order > 0 %}
                    <a href="{{ article.get_absolute_url }}"
                       rel="bookmark">【Верхняя】{{ article.title }}</a>
                {% else %}
                    <a href="{{ article.get_absolute_url }}"
                       rel="bookmark">{{ article.title }}</a>
                {% endif %}

            {% else %}
                {{ article.title }}
            {% endif %}
        </h1>
        <div class="comments-link">
            {% if article.comment_status == "o" and open_site_comment %}
                <a href="{{ article.get_absolute_url }}#comments" class="ds-thread-count" data-thread-key="3815"
                   rel="nofollow">
                    <span class="leave-reply">
                    {% if article.comment_set and article.comment_set.count %}
                        {{ article.comment_set.count }}Комментарии
                    {% else %}
                        发表评论
                    {% endif %}
                    </span>
                </a>
            {% endif %}
            <div style="float:right">
                {{ article.views }} views
            </div>
        </div><!-- .comments-link -->
        <br/>
        {% if article.type == 'a' %}
            {% if not isindex %}
                {% cache 36000 breadcrumb article.pk %}
                    {% load_breadcrumb article %}
                {% endcache %}
            {% endif %}
        {% endif %}
    </header><!-- .entry-header -->

    <div class="entry-content" itemprop="articleBody">
        {% if  isindex %}
            {{ article.body|custom_markdown|escape|truncatechars_content }}
            <p class='read-more'><a
                    href=' {{ article.get_absolute_url }}'>Подробнее</a></p>
        {% else %}

            {% if article.show_toc %}
                {% get_markdown_toc article.body as toc %}
                <b>Оглавление: </b>
                {{ toc|safe }}

                <hr class="break_line"/>
            {% endif %}
            <div class="article">

                    {{ article.body|custom_markdown|escape }}

            </div>
        {% endif %}

    </div><!-- .entry-content -->

    {% load_article_metas article user %}

</article><!-- #post -->

olgaDjangoBlog_9_01_2023/djangoblog/templates/blog/tags/article_meta_info.html
{% load blog_tags %}
{% load cache %}
{% with article.id|add:user.is_authenticated as cachekey %}
    {% cache 36000 metainfo cachekey %}
        <footer class="entry-meta">
            Эта запись была опубликована на
            <a href="{{ article.get_absolute_url }}" title="{% datetimeformat article.pub_time %}"
                     itemprop="datePublished" content="{% datetimeformat article.pub_time %}"
                     rel="bookmark">

            <time class="entry-date updated"
                  datetime="{{ article.pub_time }}">
                {% datetimeformat article.pub_time %}</time>
        </a>
            {% if article.type == 'a' %}
                . принадлежать<a href="{{ article.category.get_absolute_url }}" rel="category tag">{{ article.category.name }}</a>
                Классификация,
                {% if article.tags.all %}
                    был опубликован

                    {% for t in article.tags.all %}
                        <a href="{{ t.get_absolute_url }}" rel="tag">{{ t.name }}</a>
                        {% if t != article.tags.all.last %}
                            ，
                        {% endif %}
                    {% endfor %}

                    Этикетка.
                {% endif %}
            {% endif %}
            <span class="by-author">作者是
        <span class="author vcard">
            <a class="url fn n" href="{{ article.author.get_absolute_url }}"
               title="просмотреть все по{{ article.author.username }}опубликованные статьи"
               rel="author">
            <span itemprop="author" itemscope itemtype="http://schema.org/Person">

            <span itemprop="name" itemprop="publisher">

            {{ article.author.username }}
        </span>
            </span>
    </a>
        </span>。
                {% if user.is_superuser %}
                    <a href="{{ article.get_admin_url }}">编辑</a>
                {% endif %}
    </span>
        </footer><!-- .entry-meta -->

    {% endcache %}
{% endwith %}

olgaDjangoBlog_9_01_2023/djangoblog/templates/blog/tags/article_pagination.html
<nav id="nav-below" class="navigation" role="navigation">
    <h3 class="assistive-text">Навигация по статьям</h3>
    {% if page_obj.has_next  and next_url%}
        <div class="nav-previous"><a
                href="{{ next_url }}"><span
                class="meta-nav">&larr;</span> более ранние статьи</a></div>
    {% endif %}
    {% if page_obj.has_previous and previous_url %}
        <div class="nav-next"><a href="{{ previous_url }}">новые статьи
            <span
                    class="meta-nav">→</span></a>
        </div>
    {% endif %}
</nav><!-- .navigation -->

olgaDjangoBlog_9_01_2023/djangoblog/templates/blog/tags/article_tag_list.html
{% if article_tags_list %}
    <div class="panel panel-default">
        <div class="panel-heading">Этикетка</div>
        <div class="panel-body">

            {% for url,count,tag,color in article_tags_list %}
                <a class="label label-{{ color }}" style="display: inline-block;" href="{{ url }}"
                   title="{{ tag.name }}">
                    {{ tag.name }}
                    <span class="badge">{{ count }}</span>
                </a>
            {% endfor %}

        </div>
    </div>
{% endif %}

olgaDjangoBlog_9_01_2023/djangoblog/templates/blog/tags/breadcrumb.html
<ul itemscope itemtype="https://schema.org/BreadcrumbList" class="breadcrumb">

    {% for name,url in names %}
        <li itemprop="itemListElement" itemscope
            itemtype="https://schema.org/ListItem">
            <a href="{{ url }}" itemprop="item" >
                <span itemprop="name">{{ name }}</span></a>
            <meta itemprop="position" content="{{ forloop.counter }}"/>

        </li>
    {% endfor %}
    <li class="active" itemprop="itemListElement" itemscope
        itemtype="https://schema.org/ListItem">
        <span itemprop="name">{{ title }}</span>
        <meta itemprop="position" content="{{ count }}"/>
    </li>

</ul>

olgaDjangoBlog_9_01_2023/djangoblog/templates/blog/tags/sidebar.html
{% load blog_tags %}
<div id="secondary" class="widget-area" role="complementary">
    <aside id="search-2" class="widget widget_search">
        <form role="search" method="get" id="searchform" class="searchform" action="/search">
            <div>
                <label class="screen-reader-text" for="s">поиск:</label>
                <input type="text" value="" name="q" id="q"/>
                <input type="submit" id="searchsubmit" value="поиск"/>
            </div>
        </form>
    </aside>
    {% if extra_sidebars %}
        {% for sidebar in extra_sidebars %}

            <aside class="widget_text widget widget_custom_html"><p class="widget-title">
                {{ sidebar.name }}</p>
                <div class="textwidget custom-html-widget">
                    {{ sidebar.content|custom_markdown|safe }}
                </div>
            </aside>
        {% endfor %}
    {% endif %}
    {% if most_read_articles %}

        <aside id="views-4" class="widget widget_views"><p class="widget-title">Views</p>
            <ul>
                {% for a in most_read_articles %}
                    <li>
                        <a href="{{ a.get_absolute_url }}" title="{{ a.title }}">
                            {{ a.title }}
                        </a> - {{ a.views }} views
                    </li>
                {% endfor %}
            </ul>

        </aside>
    {% endif %}
    {% if sidebar_categorys %}
        <aside id="su_siloed_terms-2" class="widget widget_su_siloed_terms"><p class="widget-title">Категории</p>
            <ul>
                {% for c in sidebar_categorys %}
                    <li class="cat-item cat-item-184"><a href={{ c.get_absolute_url }}>{{ c.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </aside>
    {% endif %}
    {% if sidebar_comments and  open_site_comment %}
        <aside id="ds-recent-comments-4" class="widget ds-widget-recent-comments"><p class="widget-title">последние комментарии</p>
            {% comment %}<ul class="ds-recent-comments" data-num-items="5" data-show-avatars="1" data-show-time="1"
            data-show-title="1" data-show-admin="1" data-avatar-size="30" data-excerpt-length="70"></ul>{% endcomment %}
            <ul id="recentcomments">
                {% for c in sidebar_comments %}
                    <li class="recentcomments">
                <span class="comment-author-link">
                    {{ c.author.username }}</span>
                        опубликовано в"
                        <a href="{{ c.article.get_absolute_url }}#comment-{{ c.pk }}">{{ c.article.title }}</a>》
                    </li>
                {% endfor %}
            </ul>
        </aside>
    {% endif %}
    {% if recent_articles %}
        <aside id="recent-posts-2" class="widget widget_recent_entries"><p class="widget-title">последние статьи</p>
            <ul>

                {% for a in  recent_articles %}
                    <li><a href="{{ a.get_absolute_url }}" title="{{ a.title }}">
                        {{ a.title }}
                    </a></li>
                {% endfor %}
            </ul>
        </aside>
    {% endif %}
    {% if sidabar_links %}
        <aside id="linkcat-0" class="widget widget_links"><p class="widget-title">закладка</p>
            <ul class='xoxo blogroll'>
                {% for l in sidabar_links %}
                    <li>
                        <a href="{{ l.link }}" target="_blank" title="{{ l.name }}">{{ l.name }}</a>
                    </li>
                {% endfor %}

            </ul>
        </aside>
    {% endif %}
    {% if show_google_adsense %}
        <aside id="text-2" class="widget widget_text"><p class="widget-title">Google AdSense</p>
            <div class="textwidget">
                {{ google_adsense_codes|safe }}
            </div>
        </aside>
    {% endif %}
    {% if sidebar_tags %}
        <aside id="tag_cloud-2" class="widget widget_tag_cloud"><p class="widget-title">Облако тегов</p>
            <div class="tagcloud">
                {% for tag,count,size in sidebar_tags %}
                    <a href="{{ tag.get_absolute_url }}"
                       class="tag-link-{{ tag.id }} tag-link-position-{{ tag.id }}"
                       style="font-size: {{ size }}pt;" title="{{ count }}Облако тегов"> {{ tag.name }}
                    </a>
                {% endfor %}
            </div>
        </aside>
    {% endif %}
    <aside id="text-2" class="widget widget_text"><p class="widget-title">Добро пожаловать, чтобы
                пометить или разветвить
                исходный код этого сайта</p>
        <div class="textwidget">

            <p><a href="https://github.com/liangliangyy/DjangoBlog" rel="nofollow"><img
                    src="https://resource.lylinux.net/img.shields.io/github/stars/liangliangyy/djangoblog.svg?style=social&amp;label=Star"
                    alt="GitHub stars"></a> <a href="https://github.com/liangliangyy/DjangoBlog" rel="nofollow"><img
                    src="https://resource.lylinux.net/img.shields.io/github/forks/liangliangyy/djangoblog.svg?style=social&amp;label=Fork"
                    alt="GitHub forks"></a></p>
        </div>
    </aside>

    <aside id="meta-3" class="widget widget_meta"><p class="widget-title">Функции</p>
        <ul>
            <li><a href="/admin/" rel="nofollow">сайт управления</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'account:logout' %}" rel="nofollow">выход</a>
                </li>

            {% else %}
                <li><a href="{% url 'account:login' %}" rel="nofollow">Авторизоваться</a></li>
            {% endif %}
            {% if user.is_superuser %}
                <li><a href="{% url 'owntracks:show_dates' %}" target="_blank">Послужной список</a></li>
            {% endif %}
            <li><a href="http://gitbook.lylinux.net" target="_blank" rel="nofollow">GitBook</a></li>
        </ul>
    </aside>

    <div id="rocket" class="show" title="нажмите на меня вернуться к началу"></div>
</div><!-- #secondary -->