olgaDjangoBlog_2_17_03_2023/personal_portfolio/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.blogs, name='blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

olgaDjangoBlog_2_17_03_2023/personal_portfolio/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

olgaDjangoBlog_2_17_03_2023/personal_portfolio/blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    url = models.URLField(blank=True)
    date = models.DateField()

    def __str__(self):
        return self.title

olgaDjangoBlog_2_17_03_2023/personal_portfolio/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def blogs(request):
    blog = Blog.objects.order_by('-date')
    return render(request, 'blog/blogs.html', {'blogs': blog})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/details.html', {'blog': blog})

olgaDjangoBlog_2_17_03_2023/personal_portfolio/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="icon" href="{% static 'blog/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href = "i:/PythonCours/Python/OlgaProject_Archive/font/stylesheet.css" rel = "stylesheet" type = "text/css"/>
</head>

<body>

{% load static %}

    <div class="menu">
        <div class="wrap">
            <div class="logo">
                <a href="{% url 'blog:blogs' %}"><img src="{% static 'blog/logo.jpg' %}" style="width:100px; height:100px;" alt=""></a>
            </div>
        </div>

    </div>



  <div class="content">

    <div class="wrap">
      {% block content %}
      {% endblock content %}
    </div>

  </div>

</body>
</html>

olgaDjangoBlog_2_17_03_2023/personal_portfolio/blog/templates/blog/blogs.html
{% extends 'blog/base.html' %}

{% block content %}

{% load static %}

<h1>Поделки </h1>




<h2 class="count" style="align-text:left;">Постов: {{ blogs.count }}</h2>

    {% for blog in blogs %}
    <div class="element">
        <h2 class="top"><a href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a></h2>
        <div class="text">
                {% if blog.image %}
                <img src="{{ blog.image.url }}" class="image"  alt="">
                {% endif %}
            </div>
        <div class="blog_text">
            <h5>Дата создания: {{ blog.date|date:'d.m.y' }}</h5>

            <p>Описание: {{ blog.description|striptags|truncatechars:3600 }}</p>

        </div>
        <div class="text">

        </div>
    </div>
    {% endfor %}


{% endblock %}

olgaDjangoBlog_2_17_03_2023/personal_portfolio/blog/templates/blog/details.html
{% extends 'blog/base.html' %}

{% block content %}

<div class="detail">
    <div>
        <img src="{{ blog.image.url }}" class="image" style="width:200px; height:200px;"  alt="">
    </div>
    <h1>url: <a href="{{ blog.url }}" target="_blank">{{ blog.title }}</a></h1>

    <h2>--{{ blog.date|date:'j E Y' }}--</h2>

    {{ blog.description|safe }}
</div>


{% endblock %}